# Generated by Django 2.2.4 on 2019-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
