# Generated by Django 2.2.4 on 2019-09-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userextended_is_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Conductor'),
        ),
    ]
