# Generated by Django 2.2.4 on 2019-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190907_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_de_perfil', verbose_name='Foto de Perfil'),
        ),
    ]
