# Generated by Django 2.2.4 on 2019-09-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userextended_photo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPhoneFCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toke_phone', models.CharField(max_length=250, verbose_name='Token FMC')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserExtended')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('destiny', models.CharField(max_length=100, verbose_name='Destino')),
                ('type_service', models.CharField(max_length=100, verbose_name='Tipo de servicio')),
                ('disability', models.BooleanField(default=False, verbose_name='Conductor')),
                ('charge', models.BooleanField(default=False, verbose_name='Conductor')),
                ('pet', models.BooleanField(default=False, verbose_name='Conductor')),
                ('passengers', models.BooleanField(default=False, verbose_name='Conductor')),
                ('description', models.TextField(default='Sin descripción', verbose_name='Description')),
                ('state', models.CharField(default='servicio creado', max_length=100, verbose_name='Estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to='app.UserExtended')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_drive', to='app.UserExtended')),
            ],
        ),
    ]
