# Generated by Django 2.2.4 on 2019-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_service_tokenphonefcm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='destiny',
            new_name='destiny_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='origin',
            new_name='origin_name',
        ),
        migrations.AddField(
            model_name='service',
            name='destiny_lan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='destiny_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='distance',
            field=models.CharField(max_length=30, null=True, verbose_name='Distancia'),
        ),
        migrations.AddField(
            model_name='service',
            name='origin_lan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='origin_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.CharField(max_length=30, null=True, verbose_name='Tiempo estimado'),
        ),
    ]
