# Generated by Django 2.2.4 on 2019-10-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191008_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
