# Generated by Django 2.2.4 on 2019-10-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_service_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueKilometer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='cancel_reason',
            field=models.CharField(default='', max_length=100, verbose_name='Motivo cancelacion servicio'),
        ),
        migrations.AddField(
            model_name='service',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150, verbose_name='Comentario')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_client', to='app.UserExtended')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_drive', to='app.UserExtended')),
            ],
        ),
    ]
