# Generated by Django 2.2.4 on 2019-10-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191021_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score_attitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='score_carCondition',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='score_personalPresentation',
            field=models.FloatField(default=0.0),
        ),
    ]
