# Generated by Django 2.2.4 on 2019-10-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191025_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='license_plate',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='placa'),
        ),
    ]
