# Generated by Django 2.2.4 on 2019-10-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userextended_license_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.FloatField(default=0.0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
