# Generated by Django 2.2.4 on 2019-11-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191102_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprice',
            name='count_after',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='MessageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Origen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service')),
            ],
        ),
    ]
