# Generated by Django 5.0.4 on 2024-05-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_baseprice_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='status',
            field=models.CharField(default='Disponible', verbose_name='Estado del conductor'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='is_driver',
            field=models.BooleanField(default=False, null=True, verbose_name='Es conductor'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='license_plate',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Placa'),
        ),
    ]
