# Generated by Django 5.0.4 on 2024-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_service_date_reservation_service_time_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_reservation',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de reserva'),
        ),
    ]
