# Generated by Django 5.0.4 on 2024-05-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_service_time_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='time_reservation',
            new_name='reservation_time',
        ),
    ]
