# Generated by Django 5.0.4 on 2024-05-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_driverbalance_driverbalancedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverbalance',
            old_name='total_value',
            new_name='total',
        ),
    ]
