# Generated by Django 5.0.4 on 2024-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_total_value_driverbalance_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0, verbose_name='Costo a descontara por servicio')),
            ],
        ),
    ]
