# Generated by Django 5.0.4 on 2024-06-04 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_discountservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0.0, verbose_name='Total pagado')),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='creado', verbose_name='Estado')),
                ('payment_id', models.CharField(default='', max_length=100, verbose_name='Id payU')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_drive', to='app.userextended')),
            ],
        ),
    ]
