# Generated by Django 5.0.4 on 2024-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_userextended_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayment',
            name='order_id',
            field=models.CharField(default='', max_length=100, verbose_name='Order Id payU'),
        ),
    ]
