# Generated by Django 5.0.4 on 2024-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_driverpayment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayment',
            name='pse_url',
            field=models.CharField(default='', max_length=500, verbose_name='Url pse'),
        ),
    ]
